[[key]]
name = "binding_common_species"
type = "chembl:binding"
min_pchembl = 0
relations = "<,<=,=,>=,>"
taxa = "human,rat,mouse,bos taurus"

[[key]]
name = "binding_vertebrata"
type = "chembl:binding"
min_pchembl = 0
relations = "<,<=,=,>=,>"
taxa = "vertebrata"
