[[search]]
key = "binding.common_species"
source = "chembl:binding"
min_pchembl = 0
relations = "<,<=,=,>=,>"
taxa = "human,rat,mouse,bos taurus"

[[search]]
key = "binding.vertebrata"
source = "chembl:binding"
min_pchembl = 0
relations = "<,<=,=,>=,>"
taxa = "vertebrata"
