[meta]
verbose = false
to = ".csv"

[[search]]
source = "chembl:binding"
min_pchembl = 0
relations = "<,<=,=,>=,>"
taxa = "euteleostomi"

[[search]]
source = "chembl:mechanism"

[[search]]
source = "chembl:atc"

[[search]]
source = "chembl:atc"
