
[data]
allowed = ["my", "allowed", "target", "IDs"]
banned = ["my", "banned", "target", "IDs"]

[[mandos.filter.search]]
key = "my-activity-data"          # applies for this search key
# all of these are joined by an AND:
pchembl = ">= 10"                 #  =, <, <=, >, >=, and % (below)
relation = ["<", "<=", "="]       # contained in a list
target_name = "$ .*?[0-9]+$"      # regex; global and case-sensitive
taxon_id = "<< @euteleostomi"     # special; taxa names and IDs
object_name = "<< data.allowed"   # contained in a long list
